---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "profile-picture"
host: "localhost:7934"
basePath: "/api"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
- "image/png"
paths:
  /{hex}/{name}:
    get:
      description: "Get profile picture in png."
      operationId: "getPicture"
      produces:
      - "application/json"
      - "image/png"
      parameters:
      - name: "hex"
        in: "path"
        description: "Hex value of color"
        required: true
        type: "string"
      - name: "name"
        in: "path"
        description: "Your name"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "string"
        401:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    x-swagger-router-controller: "main"
definitions:
  ErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
